Repository WildCodeSchool/toulouse-0918-java-mesclubs, pull requests merged in 2018-10, with the labels that each got.

#1 add MapActivity and ListActivity
  app/build.gradle
  app/src/debug/res/values/google_maps_api.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/mesclubs/ListActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MainActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
  app/src/main/res/drawable-hdpi/listing.png
  app/src/main/res/drawable-hdpi/logo.png
  app/src/main/res/drawable-hdpi/mycat.png
  app/src/main/res/drawable-mdpi/listing.png
  app/src/main/res/drawable-mdpi/logo.png
  app/src/main/res/drawable-mdpi/mycat.png
  app/src/main/res/drawable-xhdpi/listing.png
  app/src/main/res/drawable-xhdpi/logo.png
  app/src/main/res/drawable-xhdpi/mycat.png
  app/src/main/res/drawable-xxhdpi/listing.png
  app/src/main/res/drawable-xxhdpi/logo.png
  app/src/main/res/drawable-xxhdpi/mycat.png
  app/src/main/res/drawable-xxxhdpi/listing.png
  app/src/main/res/drawable-xxxhdpi/logo.png
  app/src/main/res/drawable-xxxhdpi/mycat.png
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/values/strings.xml
  app/src/release/res/values/google_maps_api.xml
Labels: reviewed

#5 Géoloc is ok
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/mesclubs/MainActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
Labels: Relu

#7 Map
  app/src/main/java/fr/wildcodeschool/mesclubs/LocationProvider.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MainActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
Labels: Relu

#9 slide for the intent is ok
  app/src/main/java/fr/wildcodeschool/mesclubs/ListActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MainActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
  app/src/main/res/anim/slide_in_left.xml
  app/src/main/res/anim/slide_in_right.xml
  app/src/main/res/anim/slide_out_left.xml
  app/src/main/res/anim/slide_out_right.xml
Labels: Relu

#8 List
  app/src/main/java/fr/wildcodeschool/mesclubs/ClubModel.java
  app/src/main/java/fr/wildcodeschool/mesclubs/ListActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/ListAdapter.java
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/row_item_list.xml
  app/src/main/res/values/colors.xml
Labels: Relu

#4 adapter
  app/src/main/java/ListAdapter.java
Labels: invalid

#11 mFused on local variable
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
Labels: Relu

#12 add Style.xlm for slide and sense of the problem slide set
  app/src/main/java/fr/wildcodeschool/mesclubs/ListActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MainActivity.java
  app/src/main/res/values/styles.xml
Labels: Relu

#15 add enter button on splash page for skip animation
  app/src/main/java/fr/wildcodeschool/mesclubs/SplashActivity.java
  app/src/main/res/drawable-hdpi/imageview.png
  app/src/main/res/drawable-mdpi/imageview.png
  app/src/main/res/drawable-xhdpi/imageview.png
  app/src/main/res/drawable-xxhdpi/imageview.png
  app/src/main/res/drawable-xxxhdpi/imageview.png
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#16 splash pagei mproved
  app/src/main/java/fr/wildcodeschool/mesclubs/SplashActivity.java
Labels: Relu

#18 add Marker with object MarkerInfo
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
  app/src/main/res/layout/item_marker.xml
Labels: Relu

#19 resolved move and zoom camera alltime
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
Labels: Relu

#22 correction bug
  app/src/main/java/fr/wildcodeschool/mesclubs/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: Relu

#20 Tentative menu
  .idea/assetWizardSettings.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/mesclubs/LocationProvider.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MainActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/ProfilActivity.java
  app/src/main/res/drawable-hdpi/baseline_directions_black_18dp.png
  app/src/main/res/drawable-hdpi/baseline_favorite_black_18dp.png
  app/src/main/res/drawable-hdpi/baseline_filter_list_black_18dp.png
  app/src/main/res/drawable-hdpi/baseline_input_black_18dp.png
  app/src/main/res/drawable-mdpi/baseline_directions_black_18dp.png
  app/src/main/res/drawable-mdpi/baseline_favorite_black_18dp.png
  app/src/main/res/drawable-mdpi/baseline_filter_list_black_18dp.png
  app/src/main/res/drawable-mdpi/baseline_input_black_18dp.png
  app/src/main/res/drawable-v24/baseline_directions_black_18dp.png
  app/src/main/res/drawable-v24/baseline_favorite_black_18dp.png
  app/src/main/res/drawable-v24/baseline_filter_list_black_18dp.png
  app/src/main/res/drawable-v24/baseline_input_black_18dp.png
  app/src/main/res/drawable-xhdpi/baseline_directions_black_18dp.png
  app/src/main/res/drawable-xhdpi/baseline_favorite_black_18dp.png
  app/src/main/res/drawable-xhdpi/baseline_filter_list_black_18dp.png
  app/src/main/res/drawable-xhdpi/baseline_input_black_18dp.png
  app/src/main/res/drawable-xxhdpi/baseline_directions_black_18dp.png
  app/src/main/res/drawable-xxhdpi/baseline_favorite_black_18dp.png
  app/src/main/res/drawable-xxhdpi/baseline_filter_list_black_18dp.png
  app/src/main/res/drawable-xxhdpi/baseline_input_black_18dp.png
  app/src/main/res/drawable-xxxhdpi/baseline_directions_black_18dp.png
  app/src/main/res/drawable-xxxhdpi/baseline_favorite_black_18dp.png
  app/src/main/res/drawable-xxxhdpi/baseline_filter_list_black_18dp.png
  app/src/main/res/drawable-xxxhdpi/baseline_input_black_18dp.png
  app/src/main/res/drawable-xxxhdpi/chat.png
  app/src/main/res/drawable-xxxhdpi/personne.png
  app/src/main/res/drawable-xxxhdpi/round_person_black_18dp.png
  app/src/main/res/drawable/baseline_directions_black_18dp.png
  app/src/main/res/drawable/baseline_favorite_black_18dp.png
  app/src/main/res/drawable/baseline_filter_list_black_18dp.png
  app/src/main/res/drawable/baseline_input_black_18dp.png
  app/src/main/res/drawable/baseline_person_pin_black_18dp.png
  app/src/main/res/drawable/ic_menu_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/layout/activity_profil.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Relu

#27 List
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/mesclubs/ClubModel.java
  app/src/main/java/fr/wildcodeschool/mesclubs/ListActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/ListAdapter.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MainActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/SplashActivity.java
  app/src/main/res/drawable-hdpi/escalade.png
  app/src/main/res/drawable-hdpi/like.png
  app/src/main/res/drawable-hdpi/logoactivity.png
  app/src/main/res/drawable-hdpi/map.png
  app/src/main/res/drawable-hdpi/marche.png
  app/src/main/res/drawable-hdpi/mountain.png
  app/src/main/res/drawable-hdpi/natation.png
  app/src/main/res/drawable-mdpi/escalade.png
  app/src/main/res/drawable-mdpi/like.png
  app/src/main/res/drawable-mdpi/map.png
  app/src/main/res/drawable-mdpi/marche.png
  app/src/main/res/drawable-mdpi/mountain.png
  app/src/main/res/drawable-mdpi/natation.png
  app/src/main/res/drawable-xhdpi/escalade.png
  app/src/main/res/drawable-xhdpi/like.png
  app/src/main/res/drawable-xhdpi/map.png
  app/src/main/res/drawable-xhdpi/marche.png
  app/src/main/res/drawable-xhdpi/mountain.png
  app/src/main/res/drawable-xhdpi/natation.png
  app/src/main/res/drawable-xxhdpi/escalade.png
  app/src/main/res/drawable-xxhdpi/like.png
  app/src/main/res/drawable-xxhdpi/map.png
  app/src/main/res/drawable-xxhdpi/marche.png
  app/src/main/res/drawable-xxhdpi/mountain.png
  app/src/main/res/drawable-xxhdpi/natation.png
  app/src/main/res/drawable-xxxhdpi/escalade.png
  app/src/main/res/drawable-xxxhdpi/like.png
  app/src/main/res/drawable-xxxhdpi/map.png
  app/src/main/res/drawable-xxxhdpi/marche.png
  app/src/main/res/drawable-xxxhdpi/mountain.png
  app/src/main/res/drawable-xxxhdpi/natation.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/row_item_list.xml
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/strings.xml
Labels: Relu

#32 Popup
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
  app/src/main/res/drawable-hdpi/alpinisme.png
  app/src/main/res/drawable-hdpi/aviron.png
  app/src/main/res/drawable-hdpi/course.png
  app/src/main/res/drawable-hdpi/escalade.png
  app/src/main/res/drawable-hdpi/natation.png
  app/src/main/res/drawable-hdpi/plonge.png
  app/src/main/res/drawable-hdpi/rando.png
  app/src/main/res/drawable-hdpi/speleo.png
  app/src/main/res/drawable-hdpi/voile.png
  app/src/main/res/drawable-hdpi/yoga.png
  app/src/main/res/drawable-mdpi/alpinisme.png
  app/src/main/res/drawable-mdpi/aviron.png
  app/src/main/res/drawable-mdpi/course.png
  app/src/main/res/drawable-mdpi/escalade.png
  app/src/main/res/drawable-mdpi/natation.png
  app/src/main/res/drawable-mdpi/plonge.png
  app/src/main/res/drawable-mdpi/rando.png
  app/src/main/res/drawable-mdpi/speleo.png
  app/src/main/res/drawable-mdpi/voile.png
  app/src/main/res/drawable-mdpi/yoga.png
  app/src/main/res/drawable-xhdpi/alpinisme.png
  app/src/main/res/drawable-xhdpi/aviron.png
  app/src/main/res/drawable-xhdpi/course.png
  app/src/main/res/drawable-xhdpi/escalade.png
  app/src/main/res/drawable-xhdpi/natation.png
  app/src/main/res/drawable-xhdpi/plonge.png
  app/src/main/res/drawable-xhdpi/rando.png
  app/src/main/res/drawable-xhdpi/speleo.png
  app/src/main/res/drawable-xhdpi/voile.png
  app/src/main/res/drawable-xhdpi/yoga.png
  app/src/main/res/drawable-xxhdpi/alpinisme.png
  app/src/main/res/drawable-xxhdpi/aviron.png
  app/src/main/res/drawable-xxhdpi/course.png
  app/src/main/res/drawable-xxhdpi/escalade.png
  app/src/main/res/drawable-xxhdpi/natation.png
  app/src/main/res/drawable-xxhdpi/plonge.png
  app/src/main/res/drawable-xxhdpi/rando.png
  app/src/main/res/drawable-xxhdpi/speleo.png
  app/src/main/res/drawable-xxhdpi/voile.png
  app/src/main/res/drawable-xxhdpi/yoga.png
  app/src/main/res/drawable-xxxhdpi/alpinisme.png
  app/src/main/res/drawable-xxxhdpi/aviron.png
  app/src/main/res/drawable-xxxhdpi/course.png
  app/src/main/res/drawable-xxxhdpi/escalade.png
  app/src/main/res/drawable-xxxhdpi/natation.png
  app/src/main/res/drawable-xxxhdpi/plonge.png
  app/src/main/res/drawable-xxxhdpi/rando.png
  app/src/main/res/drawable-xxxhdpi/speleo.png
  app/src/main/res/drawable-xxxhdpi/voile.png
  app/src/main/res/drawable-xxxhdpi/yoga.png
Labels: Relu

#33 Tentative menu
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/fr/wildcodeschool/mesclubs/ListActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/ProfilActivity.java
  app/src/main/res/drawable-xxxhdpi/baseline_format_list_bulleted_black_18dp.png
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/activity_maps.xml
  app/src/main/res/layout/activity_profil.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/menu/drawer_view.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/file_paths.xml
  build.gradle
Labels: Relu

#65 commit last minutes
  app/src/main/java/fr/wildcodeschool/mesclubs/ListActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/LoginActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MainActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/MapsActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/ProfilActivity.java
  app/src/main/java/fr/wildcodeschool/mesclubs/Singleton.java
  app/src/main/res/layout/item_marker.xml
  app/src/main/res/values/strings.xml
Labels: Relu
